# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=256, null=True, verbose_name='Descripcion')),
                ('archivo', models.CharField(max_length=256, null=True, verbose_name='Archivo')),
                ('fecha', models.DateTimeField()),
                ('autor', models.CharField(max_length=256, null=True, verbose_name='Autor')),
            ],
        ),
    ]
