# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='fichero',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
