# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('idps', models.CharField(max_length=128, null=True, unique=True, verbose_name='Idps')),
                ('trafico', models.IntegerField(null=True, verbose_name='Trafico')),
                ('tipo', models.CharField(max_length=256, null=True, verbose_name='E/S')),
            ],
        ),
    ]
