# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Politica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politica',
            name='protocolo',
        ),
    ]
