# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Politica', '0002_remove_politica_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica',
            name='switch',
            field=models.IntegerField(null=True, verbose_name='Switch'),
        ),
    ]
