# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conmutador',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('idps', models.CharField(max_length=128, null=True, unique=True, verbose_name='Idps')),
                ('nombre', models.CharField(max_length=128, null=True, verbose_name='Nombre')),
                ('version', models.CharField(max_length=256, verbose_name='Version')),
                ('controlador', models.CharField(max_length=256, null=True, verbose_name='Controlador')),
                ('instancia', models.CharField(max_length=256, null=True, verbose_name='Instancia')),
                ('fabricante', models.CharField(max_length=256, null=True, verbose_name='Fabricante')),
            ],
        ),
    ]
